service: serverless-framework-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler

custom:
  datadog:
    site: datadoghq.com
    apiKeySecretArn: ${file(./config.yml):apiKeySecretArn}

plugins:
  - serverless-plugin-datadog
